---
title: "Dashboard, by Aaron Howard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(shiny)
library(crosstalk)
library(DT)
library(plotly)
library(scales)
library(png)
library(r2symbols)
library(kableExtra)
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=F)

#MPO
placedata <- read.csv("Place_data.csv")
placedata <- placedata[,-1]
names(placedata) <- c("Place", "Statistic", "Percent")
placedata$Percent <- round(placedata$Percent,1)
tdata_p <- SharedData$new(placedata)

strokedata <- read.csv("Stroke_data.csv")
strokedata <- strokedata[,-1]
names(strokedata) <- c("Percent", "Statistic", "Strokes")
strokedata$Strokes <- round(strokedata$Strokes,1)
strokedata$Percent <- round(strokedata$Percent,1)
strokedata$Type <- c(rep("Prediction",200),rep("Observed",16))
strokedata$stat_lab <- c(rep("",200),"C1R","C1P","C2R","C2P",rep("",12))
tdata_s <- SharedData$new(strokedata)
#remove C2P
strokedata_nc2 <- strokedata[-c(151:200,204,208,212,216),]
tdata_snc2 <- SharedData$new(strokedata_nc2)
```


Visualizations
======================================================================= 

Inputs {.sidebar}
-----------------------------------------------------------------------

Use the boxes below to subset statistics of interest into the two plots.

```{r}
filter_select("Statistic", "Choose % Stat (Top plot)", tdata_p, ~Statistic)
```

```{r}
filter_select("Statistic", "Choose Stroke Stat (Bottom plot)", tdata_s, ~Statistic)
```

Column {data-width=450}
-----------------------------------------------------------------------

### Plot of average statistic percentage (%) by finishing place (float cursor over plot for more info)

```{r}
lm.mod<-lm(Percent ~ Place*Statistic+I(Place^2)*Statistic,data=placedata)
Prediction <- predict(lm.mod)
g <- ggplot(tdata_p,aes(Place,Percent,group=Statistic)) + 
  geom_line(aes(color=Statistic),alpha=0.5) +
  geom_line(aes(y=Prediction,color=Statistic)) +
  scale_color_manual(values = c("C1P (%)" = "black", "C1R (%)" = "gray", "C2R (%)" = "red", "C2P (%)" = "blue"))+
  xlab("Finishing Place") +
  ylab("Statistic Percentage (%)")

ggplotly(g,tooltip = c("group", "x", "y"))%>%
    layout (
           yaxis = list(rangemode="normal"))
```

### Plot of strokes saved by statistic percentage (%) (float cursor over plot for more info)

```{r}
col=c(rep("black",150),rep("red",12))
s <- c(rep(1,150),rep(2,12)) 
al <- c(rep(0.5,150),rep(1,12))
h <- ggplot(data=tdata_snc2,aes(Percent,Strokes,group=Statistic,color=Type, 
                                 label = stat_lab)) + 
  geom_point(size=s,alpha=al) +
  geom_text(nudge_x = 0.25, nudge_y = 0.4)+
  scale_color_manual(values = c("Prediction" = "black", "Observed" = "red"))+
  xlab("Statistic Percentage (%)") +
  xlim(30,100)+
  ylab("Strokes Saved")

ggplotly(h,tooltip = c("x", "y","group")) %>%
    layout(yaxis = list(rangemode="normal"))
```

Column {data-width=550}
-----------------------------------------------------------------------

### {data-height=450}

#### Methods and interpretation

The predicted line is based on a linear model with a quadratic fit.  The lighter lines are the averages by finishing position.  

*Generally speaking, as finishing place increases the statistic percentages (C1P, C1R) decrease.*


### {data-height=550}

The predicted values (black dots) are based on a GLMM (generalized linear mixed effects model) that controls for tournament (random effect) and all of the major statistical categories.  This means, for example, that the change in strokes saved for C1R that you see in the plot is that value while all other statistics are held constant and the variation in scoring between events is considered.  There is a significant interaction between C2R and C2P.  That interaction is incorporated into the prediction values.

The red dots are the observed values for winners, top-10, top-20, and top-50.  All values are relative to 50th place finisher.



*As statistical percentage increases, strokes saved goes up.  This effect is STRONGEST for C1R.*


Data Tables
======================================================================= 


Column {data-width=500}
-----------------------------------------------------------------------

### Place Data: Subset by statistic, order by place or percent

```{r}
placedata %>%
  datatable(filter = 'top', options = list(
  pageLength = 25))
```


Column {data-width=500}
-----------------------------------------------------------------------

### Stroke Data: Subset by statistic and Type

```{r}
strokedata %>%
  datatable(filter = 'top', options = list(
  pageLength = 25)) 
```

