---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(shiny)
library(crosstalk)
library(DT)
library(plotly)
library(scales)
library(png)
library(r2symbols)
library(kableExtra)
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=F)

#MPO
placedata <- read.csv("Place_data.csv")
placedata <- placedata[,-1]
names(placedata) <- c("Place", "Statistic", "Percent")
tdata_p <- SharedData$new(placedata)

strokedata <- read.csv("Stroke_data.csv")
strokedata <- strokedata[,-1]
names(strokedata) <- c("Percent", "Statistic", "Strokes")
tdata_s <- SharedData$new(strokedata)
```


Stats Dashboard
======================================================================= 

Inputs {.sidebar}
-----------------------------------------------------------------------

Use the boxes below to subset statistics of interest into the two plots.

```{r}
filter_select("Statistic", "Choose % Stat (Top plot)", tdata_p, ~Statistic)
```

```{r}
filter_select("Statistic", "Choose Strokes Stat (Bottom plot)", tdata_s, ~Statistic)
```

Row
-----------------------------------------------------------------------

### Plot of statistic percentage (%) by finishing place

```{r}
g <- ggplot(tdata_p,aes(Place,Percent,group=Statistic)) + 
  geom_line(aes(color=Statistic)) +
  xlab("Finishing Place") +
  ylab("Statistic Percentage (%)")

ggplotly(g,tooltip = c("x", "y", "group"))%>%
    layout (
           yaxis = list(rangemode="normal"))
```

Row
-----------------------------------------------------------------------

### Plot of strokes saved by statistic percentage (%)

```{r}
h <- ggplot(tdata_s,aes(Percent,Strokes,group=Statistic)) + 
  geom_line(aes(color=Statistic)) +
  xlab("Statistic Percentage (%)") +
  ylab("Strokes Saved")

ggplotly(h,tooltip = c("x", "y", "group"))%>%
    layout(
           yaxis = list(rangemode="normal"))
```

